#!/usr/bin/env python3
"""
make_lbm_includes_relative.py - make the vendored LBM tree independent of the
compiler's include path, so it builds the same in PlatformIO and in the Arduino IDE.

Why: LBM includes its own headers by bare name (#include "lr1mac_defs.h") and
relies on every src/lbm/... folder being a -I directory. PlatformIO gets that
from extra_script.py. The Arduino IDE only adds this library's src/ folder; for
any header it cannot find it searches ALL other installed libraries and may use
a same-named header from one of them (for example another library that ships
its own - different - LBM copy), which breaks the build in confusing ways.

What it does (idempotent; run from anywhere after (re-)vendoring LBM):
  - rewrites every  #include "name.h"  that refers to a header inside this
    library's src/ tree into a path relative to the including file, e.g.
        #include "lr1mac_defs.h"  ->  #include "../lr1mac_defs.h"
    A relative quote-include is resolved from the including file's own folder,
    so the result no longer depends on -I order or on other libraries.
  - makes sure every LBM .c file and every own file that uses LBM starts with
    #include "<relative>/wb_lbm_config.h" (the -D flags the Arduino IDE
    cannot pass).
  - removes forwarding headers an earlier version of this script generated.
Header basenames inside src/ must be unique (the script checks).
"""
import os, re, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, "src")
OLD_TAG = "GENERATED by tools/gen_arduino_shims.py"  # old tag, only used to clean up
MARK = "/* WisBlockLoRaWAN: build flags for the Arduino IDE, see wb_lbm_config.h */"

# 0. drop forwarding headers generated by an earlier version of this tool
for f in os.listdir(src):
    p = os.path.join(src, f)
    if f.endswith(".h") and os.path.isfile(p) and OLD_TAG in open(p, errors="ignore").read(300):
        os.remove(p)

# 1. index of all headers in src/ (own + LBM)
index = {}
for d, _, files in os.walk(src):
    for f in files:
        if f.endswith(".h"):
            if f in index:
                sys.exit("duplicate header name %s:\n  %s\n  %s" % (f, index[f], os.path.join(d, f)))
            index[f] = os.path.join(d, f)

inc_re = re.compile(r'^(\s*#\s*include\s*)"([^"/\\]+)"(.*)$')
LBM_USERS = ("LoRaWANEngine.cpp", "LoRaP2PEngine.cpp", "wisblock_ral_sx126x_bsp.c",
             "wisblock_lbm_port.cpp", "wisblock_lbm_task.cpp", "wisblock_radio_hal.cpp",
             "wisblock_radio_hal_rak11310.cpp", "WisBlockLoRaWAN.cpp", "WisBlockLoRaHwConfig.cpp")

def rel(from_file, target):
    r = os.path.relpath(target, os.path.dirname(from_file)).replace(os.sep, "/")
    return r

def process(path, needs_cfg):
    raw = open(path, "rb").read().decode("utf-8", "ignore")
    crlf = "\r\n" in raw
    lines = raw.replace("\r\n", "\n").split("\n")
    changed = False
    has_cfg = any(re.match(r'\s*#\s*include\s*"[^"]*wb_lbm_config\.h"', l) for l in lines)
    for i, l in enumerate(lines):
        m = inc_re.match(l)
        if not m:
            continue
        name = m.group(2)
        target = index.get(name)
        if target is None or os.path.abspath(target) == os.path.abspath(path):
            continue
        new = '%s"%s"%s' % (m.group(1), rel(path, target), m.group(3))
        if new != l:
            lines[i] = new
            changed = True
    if needs_cfg and not has_cfg:
        for i, l in enumerate(lines):
            if re.match(r"\s*#\s*include\b", l):
                lines[i:i] = [MARK, '#include "%s"' % rel(path, index["wb_lbm_config.h"])]
                changed = True
                break
    if changed:
        out = "\n".join(lines)
        open(path, "wb").write((out.replace("\n", "\r\n") if crlf else out).encode("utf-8"))
    return changed

n_files = n_changed = 0
for d, _, files in os.walk(src):
    for f in files:
        if not f.endswith((".h", ".c", ".cpp")):
            continue
        p = os.path.join(d, f)
        in_lbm = os.path.relpath(p, src).replace(os.sep, "/").startswith("lbm/")
        needs_cfg = (in_lbm and f.endswith(".c")) or (d == src and f in LBM_USERS)
        n_files += 1
        n_changed += process(p, needs_cfg)
print("checked %d files, rewrote %d" % (n_files, n_changed))
